name: Build Brovan

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Windows x64
            runner: windows-latest
            rid: win-x64

          - platform: Linux x64
            runner: ubuntu-latest
            rid: linux-x64

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Brovan/Brovan.csproj

      - name: Publish
        run: dotnet publish Brovan/Brovan.csproj -c Release -r ${{ matrix.rid }} --self-contained false -o artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Brovan ${{ matrix.platform }}
          path: artifacts/**
